services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - db
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: laravel_webserver
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8
        container_name: laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: marketplace
            MYSQL_ROOT_PASSWORD: qwerty
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    redis:
        image: redis:alpine
        container_name: laravel_redis
        restart: unless-stopped
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
